services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stagelink
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    command: npm run dev
    env_file: .env
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app               # โค้ดในเครื่อง → คอนเทนเนอร์ (hot-reload)
      - /app/node_modules    # กัน node_modules ไม่ให้โดนทับ
      - ./uploads:/app/uploads 
    depends_on:
      - db

volumes:
  pgdata:
  uploads:
